---
name: Release

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: [ubuntu-24.04]

    permissions:
      contents: write # Required to checkout repository.
      id-token: write # Required for authentication.
      packages: write # Required to publish packages.

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: true
          persist-credentials: false

      - name: Tag release
        env:
          GH_TAG: ${{ github.event.release.tag_name}}
          GH_TOKEN: ${{ github.token }}
        run: |
          version=${GH_TAG%%.*}
          gh api /repos/${{ github.repository }}/git/refs/tags/${version} --method PATCH --silent --field sha="${GITHUB_SHA}" --field force=true || \
            gh api /repos/${{ github.repository }}/git/refs --method POST --silent --field sha="${GITHUB_SHA}" --field ref="refs/tags/${version}"

      - name: Publish package
        uses: actions/publish-immutable-action@4bc8754ffc40f27910afb20287dbbbb675a4e978 # v0.0.4
